version: '3'

services:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.4.1
    environment:
      OPENSEARCH_HOSTS: "http://opensearch-node-main:9200"
    ports:
      - 5601:5601
    links:
      - opensearch-node-main
    networks:
      - redash-searcher

  opensearch-node-main:
    image: opensearchproject/opensearch:2.4.1
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-node-main-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      - redash-searcher


volumes:
  opensearch-node-main-data:

networks:
  redash-searcher:
