name: Deploy Images

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta for web
        id: meta-web
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/ghcr.io/hiro-o918/redash-search-sync
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Docker meta for sync
        id: meta-sync
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/ghcr.io/hiro-o918/redash-search-sync
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (redash-search-sync)
        uses: docker/build-push-action@v3
        with:
          context: ./redash-search-sync
          push: true
          tags: ${{ steps.meta-sync.outputs.tags }}
          labels: ${{ steps.meta-sync.outputs.labels }}
      - name: Build and push (redash-search-web)
        uses: docker/build-push-action@v3
        with:
          context: ./redash-search-web
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
