name: Tag PR
on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-22.04
    steps:
      - uses: tibdex/github-app-token@v1
        id: github_app_token
        with:
          app_id: ${{ secrets.ORG_GITHUB_ACTIONS_APP_ID }}
          private_key: ${{ secrets.ORG_GITHUB_ACTIONS_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.github_app_token.outputs.token }}
      - name: Run tagpr
        id: run-tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ steps.github_app_token.outputs.token }}
